# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 01 - CI / CD - your-app-name

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:     
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1E1DB5481F0E4413A7EA93A2A5C3EC21 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E95C29E2012549D68BF2EEF55BE8B7C2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3C0364261FB04A429C29CA82EC230B6E }}

      - name: Check if Web App exists
        id: check_webapp
        run: |
          exists=$(az webapp show --name "your-app-name" --resource-group "test" --query "name" -o tsv || echo "")
          if [[ -n "$exists" ]]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
          
