name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permet de déclencher le workflow manuellement

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]   # Systèmes d'exploitation
        dotnet-version: [8.0,9.0]  # Versions de .NET à tester
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Navigate to the project directory
      run: cd MonApiDotNet6

    - name: Restore dependencies
      run: dotnet restore MonApiDotNet6/MonApiDotNet6.csproj  # Chemin vers le fichier .csproj

    - name: Build the project
      run: dotnet build MonApiDotNet6/MonApiDotNet6.csproj --configuration Release --output ./build_output

    - name: Run tests
      run: dotnet test MonApiDotNet6/MonApiDotNet6.csproj --configuration Release --output ./test_results

